export const SET_SOURCE_PROVIDER = "SET_SOURCE_PROVIDER";
export const SET_DESTINATION_PROVIDER = "SET_DESTINATION_PROVIDER";
export const COPY_PLAYLIST = "COPY_PLAYLIST";
export const ADD_PLAYLIST_TO_DESTINATION = "ADD_PLAYLIST_TO_DESTINATION";
export const CLOSE_STATUS_MODAL = "CLOSE_STATUS_MODAL";
export const SET_IS_COPYING_PLAYLIST = "SET_IS_COPYING_PLAYLIST";
export const ADD_FAILED_SONG_COPY = "ADD_FAILED_SONG_COPY";
export const ADD_SUCCESS_SONG_COPY = "ADD_SUCCESS_SONG_COPY";
