export const SET_DESTINATION_CURRENT_USER = "SET_DESTINATION_CURRENT_USER";
export const SET_DESTINATION_PLAYLISTS = "SET_DESTINATION_PLAYLISTS";
export const DESTINATION_LOGOUT = "DESTINATION_LOGOUT";
export const DESTNATION_REQUEST_ERROR = "REQUEST_ERROR";
export const GET_DESTINATION_PLAYLISTS = "GET_DESTINATION_PLAYLISTS";
export const DESTINATION_LOGIN = "DESTINATION_LOGIN";
