export const SET_SOURCE_CURRENT_USER = "SET_SOURCE_CURRENT_USER";
export const SET_SOURCE_PLAYLISTS = "SET_SOURCE_PLAYLISTS";
export const SOURCE_LOGOUT = "SOURCE_LOGOUT";
export const GET_SOURCE_PLAYLISTS = "GET_SOURCE_PLAYLISTS";
export const SOURCE_REQUEST_ERROR = "REQUEST_ERROR";
export const SOURCE_LOGIN = "SOURCE_LOGIN";
